const { bulkInsertGames } = require('../models/gameModel')

const sampleGames = [
  {
    title: 'The Jungle Bouldering Social',
    sport: 'bouldering',
    venue: 'Urban Climb West End',
    host_name: 'Charlie',
    starts_at: '2025-08-29 18:00:00',
    ends_at: '2025-08-29 20:00:00',
    max_players: 10,
    tags_json: ['indoor', 'social', 'beginner-friendly'],
    status: 'open',
  },
  {
    title: 'Friday Night Pickleball Doubles',
    sport: 'pickleball',
    venue: 'Brisbane Pickleball Club',
    host_name: 'Mia',
    starts_at: '2025-09-01 17:30:00',
    ends_at: '2025-09-01 19:00:00',
    max_players: 8,
    tags_json: ['outdoor', 'doubles', 'fun'],
    status: 'open',
  },
  {
    title: 'Weekend Badminton Smash',
    sport: 'badminton',
    venue: 'Sunnybank Indoor Sports Centre',
    host_name: 'Jayden',
    starts_at: '2025-09-02 14:00:00',
    ends_at: '2025-09-02 16:00:00',
    max_players: 12,
    tags_json: ['indoor', 'rally', 'all-levels'],
    status: 'open',
  },
  {
    title: 'Holland Park West Outdoor Basketball Court 1',
    sport: 'basketball',
    venue: 'Holland Park West Community Grounds',
    host_name: 'Alison',
    starts_at: '2025-08-27 16:30:00',
    ends_at: '2025-08-27 18:00:00',
    max_players: 8,
    tags_json: ['outdoor', 'half-court', 'after school'],
    status: 'open',
  },
  {
    title: 'Morning Netball Fitness',
    sport: 'netball',
    venue: 'Mt Gravatt Netball Centre',
    host_name: 'Emily',
    starts_at: '2025-09-03 07:30:00',
    ends_at: '2025-09-03 09:00:00',
    max_players: 14,
    tags_json: ['fitness', 'training', 'ladies'],
    status: 'open',
  },
  {
    title: 'Tennis Social Doubles Night',
    sport: 'tennis',
    venue: 'Queensland Tennis Centre',
    host_name: 'Lucas',
    starts_at: '2025-09-01 19:00:00',
    ends_at: '2025-09-01 21:00:00',
    max_players: 8,
    tags_json: ['night session', 'outdoor', 'mixed'],
    status: 'open',
  },
  {
    title: 'Brisbane River Run Club',
    sport: 'running',
    venue: 'South Bank Parklands',
    host_name: 'Sam',
    starts_at: '2025-08-31 06:00:00',
    ends_at: '2025-08-31 07:30:00',
    max_players: 20,
    tags_json: ['outdoor', 'sunrise', 'casual'],
    status: 'open',
  },
  {
    title: 'Friendly Volleyball Meetup',
    sport: 'volleyball',
    venue: 'Brisbane Grammar Indoor Courts',
    host_name: 'Ava',
    starts_at: '2025-08-30 18:00:00',
    ends_at: '2025-08-30 20:00:00',
    max_players: 12,
    tags_json: ['mixed team', 'friendly', 'indoor'],
    status: 'open',
  },
  {
    title: 'Casual Sunday Soccer',
    sport: 'soccer',
    venue: 'Yeronga Football Grounds',
    host_name: 'Zane',
    starts_at: '2025-09-01 15:00:00',
    ends_at: '2025-09-01 17:00:00',
    max_players: 16,
    tags_json: ['casual', 'outdoor', 'mixed-levels'],
    status: 'open',
  },
  {
    title: 'Touch Rugby Beginner Session',
    sport: 'rugby',
    venue: 'Kangaroo Point Fields',
    host_name: 'Ethan',
    starts_at: '2025-09-04 17:00:00',
    ends_at: '2025-09-04 18:30:00',
    max_players: 12,
    tags_json: ['non-contact', 'beginner', 'outdoor'],
    status: 'open',
  },
  {
    title: 'Netball Skill Session',
    sport: 'netball',
    venue: 'Carina Indoor Centre',
    host_name: 'Olivia',
    starts_at: '2025-09-02 18:00:00',
    ends_at: '2025-09-02 19:30:00',
    max_players: 10,
    tags_json: ['skill', 'training', 'indoor'],
    status: 'open',
  },
  {
    title: 'Intro to Bouldering',
    sport: 'bouldering',
    venue: '9 Degrees Brisbane',
    host_name: 'Leo',
    starts_at: '2025-08-31 10:00:00',
    ends_at: '2025-08-31 12:00:00',
    max_players: 6,
    tags_json: ['indoor', 'beginner', 'gear included'],
    status: 'open',
  },
  {
    title: 'Open Badminton Ladder',
    sport: 'badminton',
    venue: 'MacGregor State High School Hall',
    host_name: 'Grace',
    starts_at: '2025-09-03 17:00:00',
    ends_at: '2025-09-03 19:00:00',
    max_players: 16,
    tags_json: ['ladder', 'competitive', 'indoor'],
    status: 'open',
  },
  {
    title: 'Evening Tennis Singles',
    sport: 'tennis',
    venue: 'St Lucia Tennis Club',
    host_name: 'Nathan',
    starts_at: '2025-09-02 18:30:00',
    ends_at: '2025-09-02 20:00:00',
    max_players: 4,
    tags_json: ['outdoor', 'singles', 'after work'],
    status: 'open',
  },
  {
    title: 'Downtown Basketball Scrimmage',
    sport: 'basketball',
    venue: 'Brisbane City Indoor Sports',
    host_name: 'Riley',
    starts_at: '2025-09-01 20:00:00',
    ends_at: '2025-09-01 21:30:00',
    max_players: 10,
    tags_json: ['indoor', 'scrimmage', 'night'],
    status: 'open',
  },
  {
    title: 'West End Pickleball Open',
    sport: 'pickleball',
    venue: 'West End Sports Hub',
    host_name: 'Isla',
    starts_at: '2025-09-03 16:30:00',
    ends_at: '2025-09-03 18:30:00',
    max_players: 10,
    tags_json: ['intermediate', 'outdoor', 'mixed'],
    status: 'open',
  },
  {
    title: 'Co-ed Volleyball Drop-in',
    sport: 'volleyball',
    venue: 'UQ Sports Hall',
    host_name: 'Noah',
    starts_at: '2025-08-31 17:00:00',
    ends_at: '2025-08-31 19:00:00',
    max_players: 14,
    tags_json: ['drop-in', 'co-ed', 'indoor'],
    status: 'open',
  },
  {
    title: 'Beginner Rugby League Intro',
    sport: 'rugby',
    venue: 'Griffith Uni Nathan Campus Fields',
    host_name: 'Jack',
    starts_at: '2025-09-04 16:30:00',
    ends_at: '2025-09-04 18:00:00',
    max_players: 10,
    tags_json: ['intro', 'outdoor', 'non-contact'],
    status: 'open',
  },
  {
    title: 'Free Morning Run',
    sport: 'running',
    venue: 'Roma Street Parklands',
    host_name: 'Ella',
    starts_at: '2025-09-01 06:00:00',
    ends_at: '2025-09-01 07:00:00',
    max_players: 20,
    tags_json: ['sunrise', 'casual', 'community'],
    status: 'open',
  },
]

bulkInsertGames(sampleGames)
  .then(() => {
    console.log('Seeded sample games')
    process.exit()
  })
  .catch((err) => {
    console.error('Failed to seed games:', err)
    process.exit(1)
  })
